### ISSUE TITLE
Lives

### ISSUE THREAD

**Issue by BakProject** [tim-savage/SavageDeathBan#1]
Hey there! I have been looking for a plugin EXACTLY like this for 1.19.x. 

I was wondering if you were going to continue to develope this plugin, as I have a few suggestions that would amke this a PERFECT plugin for me.

* Extra lives which can be bought via in-game money.
* Permission nodes that allow you to be banned for a lesser amount of time (savagetempban.10) for 10% less ban time.

**Comment by tim-savage** [comment]
I don't have any plans to add new features to this plugin. Perhaps you can achieve your desired goals using Skript? Of course, you are always welcome to create a fork of this project to implement your own features.
